///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexMobileTest
{
    public partial class add_tocart
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void TouchAddToCart()
        {
		    /*
     		* Add to cartボタンをADB経由で直接タップする。
     		* Ranorexではボタンが独立要素として認識されないため、
     		* Android画面座標を使用して操作する。
     		*/
     		string adbPath =
     			@"C:\Users\mo_ba\AppData\Local\Android\Sdk\platform-tools\adb.exe";
     		
     		string deviceId = "emulator-5554";
     		
     		// Add to cartボタンの中央付近をタップ
     		int x = 850;
     		int y = 2214;
     		
     		Report.Info($"ADBでAdd to cartをタップします。座標: ({x}, {y})");
     		
     		var process = new System.Diagnostics.Process();
     		
     		process.StartInfo.FileName = adbPath;
     		process.StartInfo.Arguments =
     			$"-s {deviceId} shell input tap {x} {y}";
     		
     		process.Start();
     		
     		// ADB処理完了まで待機
     		process.WaitForExit();
     		
     		if (process.ExitCode != 0)
  	   		{
     			throw new Exception(
     				$"ADB tapに失敗しました。ExitCode={process.ExitCode}"
     			);
     		}
     		
     		Report.Info("ADBによるAdd to cartタップが完了しました。");		    
		}
        
        
        public void ValidateCartCount()
		{
		    /*
		     * Android UI hierarchyを取得し、
		     * カート件数「1」が表示されていることを確認する。
		     */
		
		    string adbPath =
		        @"C:\Users\mo_ba\AppData\Local\Android\Sdk\platform-tools\adb.exe";
		
		    string deviceId = "emulator-5554";
		
		    var process = new System.Diagnostics.Process();
		
		    process.StartInfo.FileName = adbPath;
		    process.StartInfo.Arguments =
		        $"-s {deviceId} shell uiautomator dump /sdcard/window.xml";
		
		    process.StartInfo.UseShellExecute = false;
		    process.StartInfo.CreateNoWindow = true;
		
		    process.Start();
		    process.WaitForExit();
		
		    // XMLをPC側へ取得
		    process.StartInfo.Arguments =
		        $"-s {deviceId} shell cat /sdcard/window.xml";
		
		    process.StartInfo.RedirectStandardOutput = true;
		
		    process.Start();
		
		    string xml = process.StandardOutput.ReadToEnd();
		
		    process.WaitForExit();
		
		    if (!xml.Contains("text=\"1\""))
		    {
		        throw new Exception("カート件数1を確認できませんでした。");
		    }
		
		    Report.Success("カート件数が1であることを確認しました。");
		}

    }
}
