///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexMobileTest
{
    public partial class cart_tocheckout
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
       	public void TouchAddToCart()
        {
		    /*
     		* Add to cartボタンをADB経由で直接タップする。
     		* Ranorexではボタンが独立要素として認識されないため、
     		* Android画面座標を使用して操作する。
     		*/
     		string adbPath =
     			@"C:\Users\mo_ba\AppData\Local\Android\Sdk\platform-tools\adb.exe";
     		
     		string deviceId = "emulator-5554";
     		
     		// Add to cartボタンの中央付近をタップ
     		int x = 850;
     		int y = 2214;
     		
     		Report.Info($"ADBでAdd to cartをタップします。座標: ({x}, {y})");
     		
     		var process = new System.Diagnostics.Process();
     		
     		process.StartInfo.FileName = adbPath;
     		process.StartInfo.Arguments =
     			$"-s {deviceId} shell input tap {x} {y}";
     		
     		process.Start();
     		
     		// ADB処理完了まで待機
     		process.WaitForExit();
     		
     		if (process.ExitCode != 0)
  	   		{
     			throw new Exception(
     				$"ADB tapに失敗しました。ExitCode={process.ExitCode}"
     			);
     		}
     		
     		Report.Info("ADBによるAdd to cartタップが完了しました。");		    
		}
                
                
    	public void TouchCartButton() 
    	{
    		/*
     		* カートアイコンをADB経由でタップする。
     		* Spyで取得したcartRLのScreenRectangleを基準に、
     		* カート領域の中央座標をタップする。
     		*/
     		
     		string adbPath =
     			 @"C:\Users\mo_ba\AppData\Local\Android\Sdk\platform-tools\adb.exe";
     		
     		string deviceId = "emulator-5554";
     		
     		
     		// cartRL: ScreenRectangle = (969, 162, 79, 79)
    		int x = 1008;
    		int y = 201;

    		Report.Info($"ADBでカートをタップします。座標: ({x}, {y})");
    		
    		var process = new System.Diagnostics.Process();
    		
    		process.StartInfo.FileName = adbPath;
    		
    		process.StartInfo.Arguments =
        		$"-s {deviceId} shell input tap {x} {y}";
     		
    		process.StartInfo.UseShellExecute = false;
		    process.StartInfo.CreateNoWindow = true;
		
		    process.Start();
		    process.WaitForExit();
		
		    if (process.ExitCode != 0)
		    {
		        throw new Exception(
		            $"カートのADBタップに失敗しました。ExitCode={process.ExitCode}"
		        );
		    }
		
		    Report.Info("ADBによるカートのタップが完了しました。");
     		
    	}
        

    }
}
