///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The cart_tocheckout recording.
    /// </summary>
    [TestModule("f7812963-92f0-4c26-8b61-6786e16c7a42", ModuleType.Recording, 1)]
    public partial class cart_tocheckout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexMobileTestRepository repository.
        /// </summary>
        public static RanorexMobileTestRepository repo = RanorexMobileTestRepository.Instance;

        static cart_tocheckout instance = new cart_tocheckout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public cart_tocheckout()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static cart_tocheckout Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "デバイス " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + " で、モバイル アプリ 'com.saucelabs.mydemoapp.android' を実行します。", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "com.saucelabs.mydemoapp.android", true, "");
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSaucelabsMydemoappAndroid.SauceLabsBackpackImage' at Center", repo.ComSaucelabsMydemoappAndroid.SauceLabsBackpackImageInfo, new RecordItemIndex(1));
            repo.ComSaucelabsMydemoappAndroid.SauceLabsBackpackImage.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            TouchAddToCart();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            Delay.Duration(3000, false);
            
            TouchCartButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1 Items') on item 'ComSaucelabsMydemoappAndroid.FragmentContainer.ItemsTV'.", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.ItemsTVInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ComSaucelabsMydemoappAndroid.FragmentContainer.ItemsTVInfo, "Text", "1 Items");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='$ 29.99') on item 'ComSaucelabsMydemoappAndroid.FragmentContainer.TotalPriceTV'.", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.TotalPriceTVInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ComSaucelabsMydemoappAndroid.FragmentContainer.TotalPriceTVInfo, "Text", "$ 29.99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSaucelabsMydemoappAndroid.FragmentContainer.CartBt' at Center", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.CartBtInfo, new RecordItemIndex(8));
            repo.ComSaucelabsMydemoappAndroid.FragmentContainer.CartBt.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Login') on item 'ComSaucelabsMydemoappAndroid.FragmentContainer.LoginTV'.", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.LoginTVInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ComSaucelabsMydemoappAndroid.FragmentContainer.LoginTVInfo, "Text", "Login");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
