///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The checkout_toLogin recording.
    /// </summary>
    [TestModule("bd2133d3-059b-49e4-93b1-3c6611dd32a0", ModuleType.Recording, 1)]
    public partial class checkout_toLogin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexMobileTestRepository repository.
        /// </summary>
        public static RanorexMobileTestRepository repo = RanorexMobileTestRepository.Instance;

        static checkout_toLogin instance = new checkout_toLogin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public checkout_toLogin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static checkout_toLogin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSaucelabsMydemoappAndroid.FragmentContainer.NameRL' at Center", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.NameRLInfo, new RecordItemIndex(0));
            repo.ComSaucelabsMydemoappAndroid.FragmentContainer.NameRL.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'bod@example.com' on item 'ComSaucelabsMydemoappAndroid.FragmentContainer.NameET'.", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.NameETInfo, new RecordItemIndex(1));
            repo.ComSaucelabsMydemoappAndroid.FragmentContainer.NameET.Element.SetAttributeValue("Text", "bod@example.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '10203040' on item 'ComSaucelabsMydemoappAndroid.FragmentContainer.PasswordET'.", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.PasswordETInfo, new RecordItemIndex(2));
            repo.ComSaucelabsMydemoappAndroid.FragmentContainer.PasswordET.Element.SetAttributeValue("Text", "10203040");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSaucelabsMydemoappAndroid.FragmentContainer.LoginBtn' at Center", repo.ComSaucelabsMydemoappAndroid.FragmentContainer.LoginBtnInfo, new RecordItemIndex(3));
            repo.ComSaucelabsMydemoappAndroid.FragmentContainer.LoginBtn.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ComSaucelabsMydemoappAndroid.shippingAdress.PaymentBtn'", repo.ComSaucelabsMydemoappAndroid.shippingAdress.PaymentBtnInfo, new ActionTimeout(5000), new RecordItemIndex(4));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.PaymentBtnInfo.WaitForExists(5000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
