///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The fill_shippingaddress recording.
    /// </summary>
    [TestModule("2cabc4a7-b58b-46bf-b151-0b15aa7537d5", ModuleType.Recording, 1)]
    public partial class fill_shippingaddress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexMobileTestRepository repository.
        /// </summary>
        public static RanorexMobileTestRepository repo = RanorexMobileTestRepository.Instance;

        static fill_shippingaddress instance = new fill_shippingaddress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public fill_shippingaddress()
        {
            FullName = "";
            AddressLine1 = "";
            City = "";
            ZipCode = "";
            Country = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static fill_shippingaddress Instance
        {
            get { return instance; }
        }

#region Variables

        string _FullName;

        /// <summary>
        /// Gets or sets the value of variable FullName.
        /// </summary>
        [TestVariable("6497c14d-6a1e-4174-88e1-6a333bb29c94")]
        public string FullName
        {
            get { return _FullName; }
            set { _FullName = value; }
        }

        string _AddressLine1;

        /// <summary>
        /// Gets or sets the value of variable AddressLine1.
        /// </summary>
        [TestVariable("02d8fa6f-2ed1-4981-9cc2-e4ea00883125")]
        public string AddressLine1
        {
            get { return _AddressLine1; }
            set { _AddressLine1 = value; }
        }

        string _City;

        /// <summary>
        /// Gets or sets the value of variable City.
        /// </summary>
        [TestVariable("e48dd6e7-3a80-4b65-bd08-fad9b101a126")]
        public string City
        {
            get { return _City; }
            set { _City = value; }
        }

        string _ZipCode;

        /// <summary>
        /// Gets or sets the value of variable ZipCode.
        /// </summary>
        [TestVariable("1fa39e84-d531-44b6-a779-e4fb75e63f7f")]
        public string ZipCode
        {
            get { return _ZipCode; }
            set { _ZipCode = value; }
        }

        string _Country;

        /// <summary>
        /// Gets or sets the value of variable Country.
        /// </summary>
        [TestVariable("c804e822-5f43-434e-ae96-889880ecc098")]
        public string Country
        {
            get { return _Country; }
            set { _Country = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            LoadRandomCheckoutData();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$FullName' on item 'ComSaucelabsMydemoappAndroid.shippingAdress.FullNameET'.", repo.ComSaucelabsMydemoappAndroid.shippingAdress.FullNameETInfo, new RecordItemIndex(1));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.FullNameET.Element.SetAttributeValue("Text", FullName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$AddressLine1' on item 'ComSaucelabsMydemoappAndroid.shippingAdress.Address1ET'.", repo.ComSaucelabsMydemoappAndroid.shippingAdress.Address1ETInfo, new RecordItemIndex(2));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.Address1ET.Element.SetAttributeValue("Text", AddressLine1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$City' on item 'ComSaucelabsMydemoappAndroid.shippingAdress.CityET'.", repo.ComSaucelabsMydemoappAndroid.shippingAdress.CityETInfo, new RecordItemIndex(3));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.CityET.Element.SetAttributeValue("Text", City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$ZipCode' on item 'ComSaucelabsMydemoappAndroid.shippingAdress.ZipET'.", repo.ComSaucelabsMydemoappAndroid.shippingAdress.ZipETInfo, new RecordItemIndex(4));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.ZipET.Element.SetAttributeValue("Text", ZipCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Country' on item 'ComSaucelabsMydemoappAndroid.shippingAdress.CountryET'.", repo.ComSaucelabsMydemoappAndroid.shippingAdress.CountryETInfo, new RecordItemIndex(5));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.CountryET.Element.SetAttributeValue("Text", Country);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComSaucelabsMydemoappAndroid.payment.PaymentBtn'.", repo.ComSaucelabsMydemoappAndroid.payment.PaymentBtnInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ComSaucelabsMydemoappAndroid.payment.PaymentBtnInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSaucelabsMydemoappAndroid.shippingAdress.PaymentBtn' at Center", repo.ComSaucelabsMydemoappAndroid.shippingAdress.PaymentBtnInfo, new RecordItemIndex(7));
            repo.ComSaucelabsMydemoappAndroid.shippingAdress.PaymentBtn.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
