///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using RanorexMobileTest.Common;

namespace RanorexMobileTest
{
    public partial class fill_shippingaddress
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        
        public void LoadRandomCheckoutData()
		{
		    /*
		     * checkout-data.csvからランダムで1件取得し、
		     * Checkout入力用変数へ設定する。
		     */
		
		    string filePath = TestDataHelper.GetTestDataPath("checkout-data.csv");
		    
		    Report.Info($"Checkout data file path: {filePath}");
		    
		    string[] values = TestDataHelper.GetRandomCsvData(filePath);

		    
		    // 必須5項目が存在することを確認
    		if (values.Length < 5)
    		{
        		throw new Exception(
            		"Checkout test data format is invalid."
        		);
    		}
			
		    // Recording Variablesへ設定
		    FullName = values[0];
		    AddressLine1 = values[1];
		    City = values[2];
		    ZipCode = values[3];
		    Country = values[4];
		
		    Report.Info(
		        $"Checkout test data selected: {FullName}, {City}, {Country}"
		    );
		}

    }
}
