///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The login_succes recording.
    /// </summary>
    [TestModule("2425dc46-24b6-47bc-a99d-0d9b1cbbffa1", ModuleType.Recording, 1)]
    public partial class login_succes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexMobileTestRepository repository.
        /// </summary>
        public static RanorexMobileTestRepository repo = RanorexMobileTestRepository.Instance;

        static login_succes instance = new login_succes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public login_succes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static login_succes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "デバイス 'emulator-5554' で、モバイル アプリ 'com.example.ranorexandroiddemo' を実行します。", new RecordItemIndex(0));
            Host.Local.RunMobileApp("emulator-5554", "com.example.ranorexandroiddemo", true, "");
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'testuser' on item 'ComExampleRanorexandroiddemo.MainActivity.EditUsername'.", repo.ComExampleRanorexandroiddemo.MainActivity.EditUsernameInfo, new RecordItemIndex(1));
            repo.ComExampleRanorexandroiddemo.MainActivity.EditUsername.Element.SetAttributeValue("Text", "testuser");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'password123' on item 'ComExampleRanorexandroiddemo.MainActivity.EditPassword'.", repo.ComExampleRanorexandroiddemo.MainActivity.EditPasswordInfo, new RecordItemIndex(2));
            repo.ComExampleRanorexandroiddemo.MainActivity.EditPassword.Element.SetAttributeValue("Text", "password123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComExampleRanorexandroiddemo.MainActivity.CheckRememberMe' at Center", repo.ComExampleRanorexandroiddemo.MainActivity.CheckRememberMeInfo, new RecordItemIndex(3));
            repo.ComExampleRanorexandroiddemo.MainActivity.CheckRememberMe.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComExampleRanorexandroiddemo.MainActivity.BtnLogin' at Center", repo.ComExampleRanorexandroiddemo.MainActivity.BtnLoginInfo, new RecordItemIndex(4));
            repo.ComExampleRanorexandroiddemo.MainActivity.BtnLogin.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'Login successful') on item 'ComExampleRanorexandroiddemo.MainActivity.TxtStatus'.", repo.ComExampleRanorexandroiddemo.MainActivity.TxtStatusInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.ComExampleRanorexandroiddemo.MainActivity.TxtStatusInfo, "Text", "Login successful");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'ComExampleRanorexandroiddemo'.", repo.ComExampleRanorexandroiddemo.SelfInfo, new RecordItemIndex(6));
            Host.Current.KillApplication(repo.ComExampleRanorexandroiddemo.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
