///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The login_failed recording.
    /// </summary>
    [TestModule("a5dd2bef-449a-4fa8-800e-bfd085b22070", ModuleType.Recording, 1)]
    public partial class Login_failed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexMobileTestRepository repository.
        /// </summary>
        public static RanorexMobileTestRepository repo = RanorexMobileTestRepository.Instance;

        static Login_failed instance = new Login_failed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_failed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_failed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "デバイス " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + " で、モバイル アプリ 'com.example.ranorexandroiddemo' を実行します。", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "com.example.ranorexandroiddemo", true, "");
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'admin' on item 'ComExampleRanorexandroiddemo.MainActivity.EditUsername'.", repo.ComExampleRanorexandroiddemo.MainActivity.EditUsernameInfo, new RecordItemIndex(1));
            repo.ComExampleRanorexandroiddemo.MainActivity.EditUsername.Element.SetAttributeValue("Text", "admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '123456' on item 'ComExampleRanorexandroiddemo.MainActivity.EditPassword'.", repo.ComExampleRanorexandroiddemo.MainActivity.EditPasswordInfo, new RecordItemIndex(2));
            repo.ComExampleRanorexandroiddemo.MainActivity.EditPassword.Element.SetAttributeValue("Text", "123456");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComExampleRanorexandroiddemo.MainActivity.CheckRememberMe' at Center", repo.ComExampleRanorexandroiddemo.MainActivity.CheckRememberMeInfo, new RecordItemIndex(3));
            repo.ComExampleRanorexandroiddemo.MainActivity.CheckRememberMe.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComExampleRanorexandroiddemo.MainActivity.BtnLogin' at Center", repo.ComExampleRanorexandroiddemo.MainActivity.BtnLoginInfo, new RecordItemIndex(4));
            repo.ComExampleRanorexandroiddemo.MainActivity.BtnLogin.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'Login failed') on item 'ComExampleRanorexandroiddemo.MainActivity.TxtStatus'.", repo.ComExampleRanorexandroiddemo.MainActivity.TxtStatusInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.ComExampleRanorexandroiddemo.MainActivity.TxtStatusInfo, "Text", "Login failed");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'ComExampleRanorexandroiddemo'.", repo.ComExampleRanorexandroiddemo.SelfInfo, new RecordItemIndex(6));
            Host.Current.KillApplication(repo.ComExampleRanorexandroiddemo.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
