///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The productlist recording.
    /// </summary>
    [TestModule("1b28652d-bc83-4a8c-b05f-cf94106e21b4", ModuleType.Recording, 1)]
    public partial class productlist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexMobileTestRepository repository.
        /// </summary>
        public static RanorexMobileTestRepository repo = RanorexMobileTestRepository.Instance;

        static productlist instance = new productlist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public productlist()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static productlist Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "デバイス " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + " で、モバイル アプリ 'com.saucelabs.mydemoapp.android' を実行します。", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "com.saucelabs.mydemoapp.android", true, "");
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sauce Labs Backpack') on item 'ComSaucelabsMydemoappAndroid.SauceLabsBackpackTitle'.", repo.ComSaucelabsMydemoappAndroid.SauceLabsBackpackTitleInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ComSaucelabsMydemoappAndroid.SauceLabsBackpackTitleInfo, "Text", "Sauce Labs Backpack");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='$ 29.99') on item 'ComSaucelabsMydemoappAndroid.SauceLabsBackpackPrice'.", repo.ComSaucelabsMydemoappAndroid.SauceLabsBackpackPriceInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ComSaucelabsMydemoappAndroid.SauceLabsBackpackPriceInfo, "Text", "$ 29.99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'ComSaucelabsMydemoappAndroid'.", repo.ComSaucelabsMydemoappAndroid.SelfInfo, new RecordItemIndex(3));
            Host.Current.KillApplication(repo.ComSaucelabsMydemoappAndroid.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
