///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexMobileTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexMobileTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("15e79e9f-44c7-4890-8a55-5745fc61106c")]
    public partial class RanorexMobileTestRepository : RepoGenBaseFolder
    {
        static RanorexMobileTestRepository instance = new RanorexMobileTestRepository();
        RanorexMobileTestRepositoryFolders.ComExampleRanorexandroiddemoAppFolder _comexampleranorexandroiddemo;
        RanorexMobileTestRepositoryFolders.ComSaucelabsMydemoappAndroidAppFolder _comsaucelabsmydemoappandroid;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexMobileTestRepository element repository.
        /// </summary>
        [RepositoryFolder("15e79e9f-44c7-4890-8a55-5745fc61106c")]
        public static RanorexMobileTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexMobileTestRepository() 
            : base("RanorexMobileTestRepository", "/", null, 0, false, "15e79e9f-44c7-4890-8a55-5745fc61106c", ".\\RepositoryImages\\RanorexMobileTestRepository15e79e9f.rximgres")
        {
            _comexampleranorexandroiddemo = new RanorexMobileTestRepositoryFolders.ComExampleRanorexandroiddemoAppFolder(this);
            _comsaucelabsmydemoappandroid = new RanorexMobileTestRepositoryFolders.ComSaucelabsMydemoappAndroidAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("15e79e9f-44c7-4890-8a55-5745fc61106c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComExampleRanorexandroiddemo folder.
        /// </summary>
        [RepositoryFolder("2087612a-7b0b-4b56-aad5-73abeee0aa85")]
        public virtual RanorexMobileTestRepositoryFolders.ComExampleRanorexandroiddemoAppFolder ComExampleRanorexandroiddemo
        {
            get { return _comexampleranorexandroiddemo; }
        }

        /// <summary>
        /// The ComSaucelabsMydemoappAndroid folder.
        /// </summary>
        [RepositoryFolder("f4764060-f210-4a41-abb0-ddf8919934dd")]
        public virtual RanorexMobileTestRepositoryFolders.ComSaucelabsMydemoappAndroidAppFolder ComSaucelabsMydemoappAndroid
        {
            get { return _comsaucelabsmydemoappandroid; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexMobileTestRepositoryFolders
    {
        /// <summary>
        /// The ComExampleRanorexandroiddemoAppFolder folder.
        /// </summary>
        [RepositoryFolder("2087612a-7b0b-4b56-aad5-73abeee0aa85")]
        public partial class ComExampleRanorexandroiddemoAppFolder : RepoGenBaseFolder
        {
            RanorexMobileTestRepositoryFolders.MainActivityFolder _mainactivity;

            /// <summary>
            /// Creates a new ComExampleRanorexandroiddemo  folder.
            /// </summary>
            public ComExampleRanorexandroiddemoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComExampleRanorexandroiddemo", "/mobileapp[@title='com.example.ranorexandroiddemo']", parentFolder, 30000, null, false, "2087612a-7b0b-4b56-aad5-73abeee0aa85", "")
            {
                _mainactivity = new RanorexMobileTestRepositoryFolders.MainActivityFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2087612a-7b0b-4b56-aad5-73abeee0aa85")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2087612a-7b0b-4b56-aad5-73abeee0aa85")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainActivity folder.
            /// </summary>
            [RepositoryFolder("c66be51e-0577-4e4d-87ba-92a94e695681")]
            public virtual RanorexMobileTestRepositoryFolders.MainActivityFolder MainActivity
            {
                get { return _mainactivity; }
            }
        }

        /// <summary>
        /// The MainActivityFolder folder.
        /// </summary>
        [RepositoryFolder("c66be51e-0577-4e4d-87ba-92a94e695681")]
        public partial class MainActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkremembermeInfo;
            RepoItemInfo _editpasswordInfo;
            RepoItemInfo _editusernameInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _txtstatusInfo;

            /// <summary>
            /// Creates a new MainActivity  folder.
            /// </summary>
            public MainActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("MainActivity", "form[@accessibilitylabel='android.widget.FrameLayout']", parentFolder, 30000, null, false, "c66be51e-0577-4e4d-87ba-92a94e695681", "")
            {
                _checkremembermeInfo = new RepoItemInfo(this, "CheckRememberMe", ".//checkbox[@accessibilityid='2131230834']", "checkbox[@accessibilityid='2131230834']", 30000, null, "81151859-fbfc-4b37-b812-2a42d45ebe99");
                _editpasswordInfo = new RepoItemInfo(this, "EditPassword", ".//text[@accessibilityid='2131230896']", "text[@accessibilityid='2131230896']", 30000, null, "9673c734-765a-4766-a0ab-d2230982ac4c");
                _editusernameInfo = new RepoItemInfo(this, "EditUsername", ".//text[@accessibilityid='2131230897']", "text[@accessibilityid='2131230897']", 30000, null, "df4e75cc-ecf4-45b6-b034-2bea57721213");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//button[@accessibilityid='2131230820']", "button[@accessibilityid='2131230820']", 30000, null, "08a0d96d-a42c-4c07-89e4-4e79c4b59195");
                _txtstatusInfo = new RepoItemInfo(this, "TxtStatus", ".//text[@accessibilityid='2131231204']", "text[@accessibilityid='2131231204']", 30000, null, "a9958bf0-8305-409f-a7c2-fe01ea481122");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c66be51e-0577-4e4d-87ba-92a94e695681")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c66be51e-0577-4e4d-87ba-92a94e695681")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckRememberMe item.
            /// </summary>
            [RepositoryItem("81151859-fbfc-4b37-b812-2a42d45ebe99")]
            public virtual Ranorex.CheckBox CheckRememberMe
            {
                get
                {
                    return _checkremembermeInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckRememberMe item info.
            /// </summary>
            [RepositoryItemInfo("81151859-fbfc-4b37-b812-2a42d45ebe99")]
            public virtual RepoItemInfo CheckRememberMeInfo
            {
                get
                {
                    return _checkremembermeInfo;
                }
            }

            /// <summary>
            /// The EditPassword item.
            /// </summary>
            [RepositoryItem("9673c734-765a-4766-a0ab-d2230982ac4c")]
            public virtual Ranorex.Text EditPassword
            {
                get
                {
                    return _editpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EditPassword item info.
            /// </summary>
            [RepositoryItemInfo("9673c734-765a-4766-a0ab-d2230982ac4c")]
            public virtual RepoItemInfo EditPasswordInfo
            {
                get
                {
                    return _editpasswordInfo;
                }
            }

            /// <summary>
            /// The EditUsername item.
            /// </summary>
            [RepositoryItem("df4e75cc-ecf4-45b6-b034-2bea57721213")]
            public virtual Ranorex.Text EditUsername
            {
                get
                {
                    return _editusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EditUsername item info.
            /// </summary>
            [RepositoryItemInfo("df4e75cc-ecf4-45b6-b034-2bea57721213")]
            public virtual RepoItemInfo EditUsernameInfo
            {
                get
                {
                    return _editusernameInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("08a0d96d-a42c-4c07-89e4-4e79c4b59195")]
            public virtual Ranorex.Button BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("08a0d96d-a42c-4c07-89e4-4e79c4b59195")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The TxtStatus item.
            /// </summary>
            [RepositoryItem("a9958bf0-8305-409f-a7c2-fe01ea481122")]
            public virtual Ranorex.Text TxtStatus
            {
                get
                {
                    return _txtstatusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtStatus item info.
            /// </summary>
            [RepositoryItemInfo("a9958bf0-8305-409f-a7c2-fe01ea481122")]
            public virtual RepoItemInfo TxtStatusInfo
            {
                get
                {
                    return _txtstatusInfo;
                }
            }
        }

        /// <summary>
        /// The ComSaucelabsMydemoappAndroidAppFolder folder.
        /// </summary>
        [RepositoryFolder("f4764060-f210-4a41-abb0-ddf8919934dd")]
        public partial class ComSaucelabsMydemoappAndroidAppFolder : RepoGenBaseFolder
        {
            RanorexMobileTestRepositoryFolders.FragmentContainerFolder _fragmentcontainer;
            RepoItemInfo _saucelabsbackpacktitleInfo;
            RepoItemInfo _saucelabsbackpackpriceInfo;
            RepoItemInfo _saucelabsbackpackimageInfo;
            RepoItemInfo _productdetailtitleInfo;
            RepoItemInfo _productdetailpriceInfo;
            RepoItemInfo _addtocartllInfo;

            /// <summary>
            /// Creates a new ComSaucelabsMydemoappAndroid  folder.
            /// </summary>
            public ComSaucelabsMydemoappAndroidAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComSaucelabsMydemoappAndroid", "/mobileapp[@title='com.saucelabs.mydemoapp.android']", parentFolder, 30000, null, false, "f4764060-f210-4a41-abb0-ddf8919934dd", "")
            {
                _fragmentcontainer = new RanorexMobileTestRepositoryFolders.FragmentContainerFolder(this);
                _saucelabsbackpacktitleInfo = new RepoItemInfo(this, "SauceLabsBackpackTitle", "form[@accessibilitylabel='android.widget.FrameLayout']/androidelement[@accessibilityid='16908290']//container[@accessibilityid='2131362091']/?/?/androidelement[@accessibilityid='2131362333']/?/?/androidelement[@accessibilityid='2131362301']/?/?/text[@accessibilityid='2131362460']", ".//text[@accessibilityid='2131362460']", 30000, null, "857e9dd1-088d-40b2-9f10-057bdc83015c");
                _saucelabsbackpackpriceInfo = new RepoItemInfo(this, "SauceLabsBackpackPrice", "form[@accessibilitylabel='android.widget.FrameLayout']/androidelement[@accessibilityid='16908290']//container[@accessibilityid='2131362091']/?/?/androidelement[@accessibilityid='2131362333']/?/?/androidelement[@accessibilityid='2131362301']/?/?/text[@accessibilityid='2131362298']", ".//text[@accessibilityid='2131362298']", 30000, null, "5edeca35-1a52-4b3a-86fd-ec6acba823bf");
                _saucelabsbackpackimageInfo = new RepoItemInfo(this, "SauceLabsBackpackImage", "form[@accessibilitylabel='android.widget.FrameLayout']/androidelement[@accessibilityid='16908290']//container[@accessibilityid='2131362091']/?/?/androidelement[@accessibilityid='2131362333']/?/?/androidelement[@accessibilityid='2131362301']/?/?/picture[@accessibilityid='2131362300']", ".//picture[@accessibilityid='2131362300']", 30000, null, "65cec7b1-4e00-4c5d-bd95-4f5a8ab1ec14");
                _productdetailtitleInfo = new RepoItemInfo(this, "ProductDetailTitle", "form[@accessibilitylabel='android.widget.FrameLayout']/androidelement[@accessibilityid='16908290']//container[@accessibilityid='2131362091']//text[@accessibilityid='2131362302']", ".//text[@accessibilityid='2131362302']", 30000, null, "d7015b1c-0b6f-421c-972f-ce92235bdb64");
                _productdetailpriceInfo = new RepoItemInfo(this, "ProductDetailPrice", "form[@accessibilitylabel='android.widget.FrameLayout']/androidelement[@accessibilityid='16908290']//container[@accessibilityid='2131362091']//container[@accessibilityid='2131362309']/text[@accessibilityid='2131362298']", ".//text[@accessibilityid='2131362298']", 30000, null, "0ec9d3f2-272b-44ee-bcfd-e36e11770ffd");
                _addtocartllInfo = new RepoItemInfo(this, "AddToCartLL", "form[@accessibilitylabel='android.widget.FrameLayout']/androidelement[@accessibilityid='16908290']//container[@accessibilityid='2131362091']//container[@accessibilityid='2131361867']", ".//container[@accessibilityid='2131361867']", 30000, null, "d0dd13a5-9289-482e-8229-7f000b5292d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f4764060-f210-4a41-abb0-ddf8919934dd")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f4764060-f210-4a41-abb0-ddf8919934dd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SauceLabsBackpackTitle item.
            /// </summary>
            [RepositoryItem("857e9dd1-088d-40b2-9f10-057bdc83015c")]
            public virtual Ranorex.Text SauceLabsBackpackTitle
            {
                get
                {
                    return _saucelabsbackpacktitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SauceLabsBackpackTitle item info.
            /// </summary>
            [RepositoryItemInfo("857e9dd1-088d-40b2-9f10-057bdc83015c")]
            public virtual RepoItemInfo SauceLabsBackpackTitleInfo
            {
                get
                {
                    return _saucelabsbackpacktitleInfo;
                }
            }

            /// <summary>
            /// The SauceLabsBackpackPrice item.
            /// </summary>
            [RepositoryItem("5edeca35-1a52-4b3a-86fd-ec6acba823bf")]
            public virtual Ranorex.Text SauceLabsBackpackPrice
            {
                get
                {
                    return _saucelabsbackpackpriceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SauceLabsBackpackPrice item info.
            /// </summary>
            [RepositoryItemInfo("5edeca35-1a52-4b3a-86fd-ec6acba823bf")]
            public virtual RepoItemInfo SauceLabsBackpackPriceInfo
            {
                get
                {
                    return _saucelabsbackpackpriceInfo;
                }
            }

            /// <summary>
            /// The SauceLabsBackpackImage item.
            /// </summary>
            [RepositoryItem("65cec7b1-4e00-4c5d-bd95-4f5a8ab1ec14")]
            public virtual Ranorex.Picture SauceLabsBackpackImage
            {
                get
                {
                    return _saucelabsbackpackimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The SauceLabsBackpackImage item info.
            /// </summary>
            [RepositoryItemInfo("65cec7b1-4e00-4c5d-bd95-4f5a8ab1ec14")]
            public virtual RepoItemInfo SauceLabsBackpackImageInfo
            {
                get
                {
                    return _saucelabsbackpackimageInfo;
                }
            }

            /// <summary>
            /// The ProductDetailTitle item.
            /// </summary>
            [RepositoryItem("d7015b1c-0b6f-421c-972f-ce92235bdb64")]
            public virtual Ranorex.Text ProductDetailTitle
            {
                get
                {
                    return _productdetailtitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProductDetailTitle item info.
            /// </summary>
            [RepositoryItemInfo("d7015b1c-0b6f-421c-972f-ce92235bdb64")]
            public virtual RepoItemInfo ProductDetailTitleInfo
            {
                get
                {
                    return _productdetailtitleInfo;
                }
            }

            /// <summary>
            /// The ProductDetailPrice item.
            /// </summary>
            [RepositoryItem("0ec9d3f2-272b-44ee-bcfd-e36e11770ffd")]
            public virtual Ranorex.Text ProductDetailPrice
            {
                get
                {
                    return _productdetailpriceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProductDetailPrice item info.
            /// </summary>
            [RepositoryItemInfo("0ec9d3f2-272b-44ee-bcfd-e36e11770ffd")]
            public virtual RepoItemInfo ProductDetailPriceInfo
            {
                get
                {
                    return _productdetailpriceInfo;
                }
            }

            /// <summary>
            /// The AddToCartLL item.
            /// </summary>
            [RepositoryItem("d0dd13a5-9289-482e-8229-7f000b5292d5")]
            public virtual Ranorex.Container AddToCartLL
            {
                get
                {
                    return _addtocartllInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AddToCartLL item info.
            /// </summary>
            [RepositoryItemInfo("d0dd13a5-9289-482e-8229-7f000b5292d5")]
            public virtual RepoItemInfo AddToCartLLInfo
            {
                get
                {
                    return _addtocartllInfo;
                }
            }

            /// <summary>
            /// The FragmentContainer folder.
            /// </summary>
            [RepositoryFolder("2328e120-95dd-4df0-bd22-1324b24e8d9f")]
            public virtual RanorexMobileTestRepositoryFolders.FragmentContainerFolder FragmentContainer
            {
                get { return _fragmentcontainer; }
            }
        }

        /// <summary>
        /// The FragmentContainerFolder folder.
        /// </summary>
        [RepositoryFolder("2328e120-95dd-4df0-bd22-1324b24e8d9f")]
        public partial class FragmentContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cartbtInfo;
            RepoItemInfo _itemstvInfo;
            RepoItemInfo _totalpricetvInfo;
            RepoItemInfo _logintvInfo;

            /// <summary>
            /// Creates a new FragmentContainer  folder.
            /// </summary>
            public FragmentContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("FragmentContainer", "form[@accessibilitylabel='android.widget.FrameLayout']//container[@accessibilityid='2131362091']", parentFolder, 30000, null, false, "2328e120-95dd-4df0-bd22-1324b24e8d9f", "")
            {
                _cartbtInfo = new RepoItemInfo(this, "CartBt", ".//androidelement[@accessibilityid='2131361921']/container[@accessibilityid='2131361922']/button[@accessibilityid='2131361941']", "", 30000, null, "70c67af1-f79f-4a86-a7b5-0cf84ae47ca3");
                _itemstvInfo = new RepoItemInfo(this, "ItemsTV", "?/?/androidelement[@accessibilityid='2131361942']/androidelement[@accessibilityid='2131361921']/container[@accessibilityid='2131361922']/?/?/text[@accessibilityid='2131362137']", "", 30000, null, "923cf5cd-b486-4a37-b97a-fed09ee4fbfc");
                _totalpricetvInfo = new RepoItemInfo(this, "TotalPriceTV", "?/?/androidelement[@accessibilityid='2131361942']/androidelement[@accessibilityid='2131361921']/container[@accessibilityid='2131361922']/?/?/text[@accessibilityid='2131362471']", "", 30000, null, "2e3cd7b2-0d16-4eef-982a-fcd6854e6786");
                _logintvInfo = new RepoItemInfo(this, "LoginTV", ".//text[@accessibilityid='2131362163']", "", 30000, null, "15ab32c2-b85f-4bc9-bfe2-8bb4a75c2d47");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2328e120-95dd-4df0-bd22-1324b24e8d9f")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2328e120-95dd-4df0-bd22-1324b24e8d9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CartBt item.
            /// </summary>
            [RepositoryItem("70c67af1-f79f-4a86-a7b5-0cf84ae47ca3")]
            public virtual Ranorex.Button CartBt
            {
                get
                {
                    return _cartbtInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CartBt item info.
            /// </summary>
            [RepositoryItemInfo("70c67af1-f79f-4a86-a7b5-0cf84ae47ca3")]
            public virtual RepoItemInfo CartBtInfo
            {
                get
                {
                    return _cartbtInfo;
                }
            }

            /// <summary>
            /// The ItemsTV item.
            /// </summary>
            [RepositoryItem("923cf5cd-b486-4a37-b97a-fed09ee4fbfc")]
            public virtual Ranorex.Text ItemsTV
            {
                get
                {
                    return _itemstvInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ItemsTV item info.
            /// </summary>
            [RepositoryItemInfo("923cf5cd-b486-4a37-b97a-fed09ee4fbfc")]
            public virtual RepoItemInfo ItemsTVInfo
            {
                get
                {
                    return _itemstvInfo;
                }
            }

            /// <summary>
            /// The TotalPriceTV item.
            /// </summary>
            [RepositoryItem("2e3cd7b2-0d16-4eef-982a-fcd6854e6786")]
            public virtual Ranorex.Text TotalPriceTV
            {
                get
                {
                    return _totalpricetvInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TotalPriceTV item info.
            /// </summary>
            [RepositoryItemInfo("2e3cd7b2-0d16-4eef-982a-fcd6854e6786")]
            public virtual RepoItemInfo TotalPriceTVInfo
            {
                get
                {
                    return _totalpricetvInfo;
                }
            }

            /// <summary>
            /// The LoginTV item.
            /// </summary>
            [RepositoryItem("15ab32c2-b85f-4bc9-bfe2-8bb4a75c2d47")]
            public virtual Ranorex.Text LoginTV
            {
                get
                {
                    return _logintvInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LoginTV item info.
            /// </summary>
            [RepositoryItemInfo("15ab32c2-b85f-4bc9-bfe2-8bb4a75c2d47")]
            public virtual RepoItemInfo LoginTVInfo
            {
                get
                {
                    return _logintvInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
